### ISSUE TITLE
Dummy character

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#10]
A dummy actor should be present to test the gravitational effects of being shot.

**Comment by sinksinksink** [comment]
In hindsight I don't think that this is necessary since we've implemented changing gravity effects on the player with a hotkey for now. 

If you're happy @shauncg, I'll close this.

**Comment by shauncg** [comment]
Sure, sounds fine to me. We may need a dummy actor later for other purposes but can open a new ticket.

**Comment by sinksinksink** [comment]
Closed! I think that's 3 to go.
