### ISSUE TITLE
Basic shield 'weapon'

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#11]
Basics implemented - some graphical representation without any effect on world (suggest a light?). 

If this is supposed to affect health this could be implemented? @shauncg  please comment on how this should work.

**Comment by shauncg** [comment]
Yeah, a glow effect (point light?) would be nice. Not sure if it would be useful / desirable in the final game but during devt could be good. 

Shield won't affect health, it only: 

(1) deflects all (friendly/enemy) beams at a 90 degree x/y angle in direction of the player's facing

(2) initiates a 'push' affect in a limited distance forwards from player facing on deployment (i.e. not continuous)

Beam also cannot be fired when shield is deployed, it is either/or.

**Comment by sinksinksink** [comment]
I've added a pointlight that is on when you hold RMB. Can build off this event later on for the other functionality. Closing this.
