### ISSUE TITLE
Physics! (branched)

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#13]
Functionality to alter gravity for the player as this is integral to the game. This will probably be tied to a key for now. Hopefully can do some work on bouncing off stuff too. 

I'm going to work on this as a separate branch, @shauncg , so as to not interfere with current development. This means changes won't be seen on the master branch we've been working on until I merge it back in (when it works). 

This will benefit level testing at a later date.

**Comment by shauncg** [comment]
Sounds sensible; also gives us a chance to work out how branching & re-integration works in a fairly neutral environment (i.e. I don't imagine that anything I'm currently assigned is going to overlap with this).

**Comment by sinksinksink** [comment]
Simple physics change implemented as well as projectile collisions affecting the heat level.
