### ISSUE TITLE
Projectile (laser) stage 2 - beam and reflection

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#27]
The laser should bounce off objects like hitting a mirror, and have a beam like look.

**Comment by sinksinksink** [comment]
Improved particle beam, physics are still messing up. Velocity is not affected by character lookup yet.

**Comment by sinksinksink** [comment]
Pitch is now correct.

**Comment by shauncg** [comment]
This definitely looks much cooler now. Progress!

**Comment by sinksinksink** [comment]
Closing this, beam isn't finished (no reflections) but it behaves well and causes damage correctly.
