### ISSUE TITLE
2x potential levels 'blocked out'

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#38]

**Comment by sinksinksink** [comment]
This is the playlist I used (didn't follow it but useful for methodology): https://www.youtube.com/playlist?list=PLZlv_N0_O1gak1_FoAJVrEGiLIploeF3F

If you need any starter content materials/textures the best thing to do is to create a new project (call it starter content or something) and select the starter content option. From this new project you can right click on a material/texture and choose 'migrate' to move it and all of it's dependencies to the FlyingDrunks project. I may add a few myself to start with.

**Comment by shauncg** [comment]
One (finally) done, sorry it's taken so long! 

Will sort a second this week now that I'm more comfortable with Unreal.

**Comment by shauncg** [comment]
Completed: Factory & Maze levels.
