### ISSUE TITLE
Projectile look and attributes

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#40]
Work to get this in a more final state. 

- Currently can hit owning player on launch if running.
- Not visible if too close to target
- The look needs refining
- Fire rate needs increasing
- Possible change to a tracer weapon (if particles can do this)

**Comment by sinksinksink** [comment]
Changed projectile to a tracer system. We should be able to work with particles to create a visual.

**Comment by sinksinksink** [comment]
Added basic sparks

**Comment by sinksinksink** [comment]
Visual added, still a few problems - spawn lags behind player position a little, goes through objects. Think the particle system needs some params.

**Comment by shauncg** [comment]
Closed, constant fire / ray source issue pushed to 0.3.5
