### ISSUE TITLE
Source control

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#46]
Just to ensure we're both using the same system. 

I've discovered using Unreal's own source control in combination with Git is excellent and will enable us to resolve conflicts much easier (since they'll probably become more likely). 

<b>Setup:</b>

- Load up UE4 FlyingDrunks editor and choose 'connect to source' from the source control menu and select Git. That should be it for setup.

<b>For general use:</b> 

- To commit after changes, choose 'submit to source control' from the source control menu in the UE4 editor. 
- Save files as prompted (you don't need to do this beforehand)
- Type commit message in dialog as prompted with list of files and submit. You should get feedback that the commit is done
- Push from command line (I don't know if there's also a way to do this from editor but it works this way)

<b>Pulling/syncing:</b>

- For pulling, you can either use the command line or right click on an asset and choose source control > sync. It may tell you automatically if the asset is out of date with the remote repo (via icon, see attached) but I haven't been able to test this. 

See attached for other icons that appear on assets.

Please close this when you're happy with it and it all works and such. It seems to be a more simple workflow than before with the slightly uncertain 'Add' commands! 

![ue4sc](https://cloud.githubusercontent.com/assets/11949891/8520907/a83ac206-23d6-11e5-9b21-5b334d1857e2.png)

**Comment by shauncg** [comment]
You are right, this is very nice.
