### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#5]
Currently there is a problem with the folder structures. Shaun's version has the project in a subfolder called FlyingDrunks which is unncessary as it should be in the root of the local Git working folder (local repository).

Suggest the following:

1) Pull most recent version to Shaun's PC.
2) Copy and paste all files in the FlyingDrunks subfolder version into root directory (up one level from current) but DO NOT overwrite any files when doing so as the files that exist in both locations are correct in the root (and match what is uploaded here).
3) Delete subfolder.
4) Add and commit files.
5) Check project works in new location.
6) Push to master.

Please close this issue when resolved. :)

**Comment by sinksinksink** [comment]
After this is resolved I think we should base folder structure on this: 

https://wiki.unrealengine.com/Assets_Naming_Convention

**Comment by shauncg** [comment]
Resolved
